'use strict';

// ─── Supported Languages ────────────────────────────────────────────────────
const LANGUAGES = {
  'zh-TW': '中文（繁體）',
  'en':    'English',
};

// ─── Translation Data ───────────────────────────────────────────────────────
// zh-TW and en are fully populated — t() falls back to zh-TW for any missing key.
const LANG_DATA = {
  'zh-TW': {
    // 導航
    'nav.home': '首頁',
    'nav.quest': '任務',
    'nav.explore': '探索',
    'nav.shop': '商店',
    'nav.settings': '設定',
    // 主頁
    'home.feed': '餵食',
    'home.drink': '飲料',
    'home.item': '道具',
    'home.pet': '寵物',
    'home.info': '資訊',
    'home.collection': '圖鑑',
    'home.manage': '管理',
    'home.focus': '專注',
    'toast.coming_soon': '即將推出！',
    // 專注計時器
    'focus.title': '專注',
    'focus.new': '＋ 新標籤',
    'focus.edit': '編輯',
    'focus.delete': '刪除',
    'focus.name': '任務名稱',
    'focus.time': '時間（分鐘）',
    'focus.start': '開始',
    'focus.pause': '暫停',
    'focus.resume': '繼續',
    'focus.stop': '結束',
    'focus.complete': '專注完成！',
    'focus.back': '← 返回',
    'focus.save': '儲存',
    'focus.cancel': '取消',
    // 寵物詳細頁面
    'pet.detail.title': '寵物詳細',
    'pet.detail.stats': '戰鬥屬性',
    'pet.detail.skills': '技能',
    'stat.rarity': '稀有度',
    'skill.power': '威力',
    // 寵物操作彈窗
    'pet.action.detail': '查看詳細',
    'pet.action.remove': '移回寵物背包',
    'pet.action.cancel': '取消',
    // 背包
    'bag.food': '食物',
    'bag.drink': '飲料',
    'bag.item': '道具',
    'bag.pet': '寵物',
    'bag.empty.food': '背包沒有食物，去商店購買吧！',
    'bag.empty.drink': '背包沒有飲料，去商店購買吧！',
    'bag.empty.item': '背包沒有道具，去商店購買吧！',
    'bag.empty.pet': '背包沒有寵物，去扭蛋機抽吧！',
    // 商店
    'shop.title': '商店',
    'shop.subtitle': '銀行與商店',
    'shop.back': '← 返回',
    'shop.bank': '能量銀行',
    'shop.bank.desc': '兌換存儲管理像素晶石',
    'shop.food.name': '食物商店',
    'shop.drink.name': '飲料商店',
    'shop.item.name': '道具商店',
    'shop.petshop': '寵物商店',
    'shop.snack': '零食商店',
    'shop.style': '形象商店',
    'shop.gacha': '扭蛋機',
    'shop.view': '查看',
    'shop.food.desc': '購買食物',
    'shop.drink.desc': '購買飲料',
    'shop.item.desc': '購買寵物道具',
    'shop.gacha.desc': '抽取稀有寵物',
    'shop.item.section': '道具',
    'food.shop.title': '食物商店',
    'drink.shop.title': '飲料商店',
    // 扭蛋
    'gacha.title': '寵物抽獎',
    'gacha.pool': '常駐卡池',
    'gacha.single': '單次抽獎',
    'gacha.ten': '十次抽獎',
    'gacha.ad': '看廣告抽一次',
    'gacha.new': 'NEW！',
    'gacha.owned': '已擁有',
    // 廣告
    'ad.watch': '觀看廣告',
    'ad.watching': '廣告播放中...',
    'ad.reward': '廣告獎勵',
    'ad.limit': '今日已達上限',
    'ad.free_gacha': '看廣告抽一次',
    'ad.count': '觀看廣告',
    'ad.reward.toast': '廣告獎勵 +50 能量石！',
    'ad.gacha.toast': '免費抽獎獲得！',
    // 道具
    'item.heart_candy': '愛心糖',
    'item.heart_candy.desc': '+10 心情',
    'item.growth_potion': '成長藥',
    'item.growth_potion.desc': '+10 EXP',
    'item.boss_ticket': 'BOSS 挑戰卷',
    'item.boss_ticket.desc': '可挑戰任意已解鎖的 BOSS，一張只能使用一次',
    'item.boss_ticket.goto': '前往 BOSS 挑戰使用',
    'item.use': '使用',
    'item.super_growth': '超級成長藥',
    'item.super_growth.desc': '使用後寵物直接升到等級上限',
    'item.super_growth.used': '超級成長藥使用！寵物升到最高等級！',
    'item.super_growth.maxed': '寵物已經是最高等級了！',
    // 探索
    'explore.title': '探索',
    'explore.subtitle': '選擇探索模式',
    'explore.world': '探索世界',
    'explore.boss': 'BOSS 挑戰',
    'explore.mystery': '神秘商店',
    'explore.go': '出去玩',
    'explore.go.desc': '在真實地圖上收集寶箱',
    'explore.boss.desc': '挑戰強大 BOSS 獲得稀有獎勵',
    // BOSS
    'boss.title': 'BOSS 挑戰',
    'boss.locked': '🔒 未解鎖',
    'boss.ticket': '🎫 使用挑戰卷挑戰',
    'boss.need_ticket': '🎫 需要挑戰卷',
    // 寵物名稱
    'pet.pet1.name': '小狗', 'pet.pet2.name': '柴犬', 'pet.pet3.name': '臘腸狗', 'pet.pet4.name': '柯基',
    'pet.pet5.name': '比格犬', 'pet.pet6.name': '米克斯', 'pet.pet7.name': '貴賓狗', 'pet.pet8.name': '比熊',
    'pet.pet9.name': '德牧', 'pet.pet10.name': '邊牧', 'pet.pet11.name': '伯恩山', 'pet.pet12.name': '牧羊犬',
    'pet.pet13.name': '橘貓', 'pet.pet14.name': '灰貓', 'pet.pet15.name': '白貓', 'pet.pet16.name': '黑貓',
    'pet.pet17.name': '英國短毛貓', 'pet.pet18.name': '牛奶貓', 'pet.pet19.name': '布偶貓', 'pet.pet20.name': '三花貓',
    'pet.pet21.name': '波斯貓', 'pet.pet22.name': '緬因貓', 'pet.pet23.name': '狐狸', 'pet.pet24.name': '小豬',
    'pet.pet25.name': '麝香豬', 'pet.pet26.name': '灰兔', 'pet.pet27.name': '黑兔', 'pet.pet28.name': '白兔',
    'pet.pet29.name': '道奇兔', 'pet.pet30.name': '庫你迷你豬', 'pet.pet31.name': '迷你豬', 'pet.pet32.name': '長耳兔',
    'pet.pet33.name': '海福特牛', 'pet.pet34.name': '牡丹鸚鵡', 'pet.pet35.name': '折衷鸚鵡', 'pet.pet36.name': '虎皮鸚鵡',
    'pet.pet37.name': '玄風鸚鵡', 'pet.pet38.name': '非洲灰鸚鵡', 'pet.pet39.name': '鳳頭巴丹鸚鵡', 'pet.pet40.name': '雞',
    'pet.pet41.name': '小鴨', 'pet.pet42.name': '水豚', 'pet.pet43.name': '樹麻雀', 'pet.pet44.name': '紅頭山雀',
    'pet.pet45.name': '黃牛', 'pet.pet46.name': '荷斯坦牛', 'pet.pet47.name': '浣熊', 'pet.pet48.name': '山羌',
    'pet.pet49.name': '梅花鹿', 'pet.pet50.name': '綿羊', 'pet.pet51.name': '紅浣熊',
    // BOSS寵物名稱
    'pet.boss_pet_01.name': '金剛鸚鵡', 'pet.boss_pet_02.name': '蟒蛇', 'pet.boss_pet_03.name': '鴕鳥', 'pet.boss_pet_04.name': '狼',
    'pet.boss_pet_05.name': '袋鼠', 'pet.boss_pet_06.name': '獵豹', 'pet.boss_pet_07.name': '河馬', 'pet.boss_pet_08.name': '犀牛',
    'pet.boss_pet_09.name': '棕熊', 'pet.boss_pet_10.name': '貓頭鷹', 'pet.boss_pet_11.name': '大猩猩', 'pet.boss_pet_12.name': '藏獒',
    'pet.boss_pet_13.name': '鱷魚', 'pet.boss_pet_14.name': '老鷹', 'pet.boss_pet_15.name': '獅子', 'pet.boss_pet_16.name': '老虎',
    // 寵物屬性（屬性名稱不翻譯，用圖示區分）
    // 水屬性
    'pet.pet1.element': '水',
    'pet.pet5.element': '水',
    'pet.pet13.element': '水',
    'pet.pet18.element': '水',
    'pet.pet19.element': '水',
    'pet.pet35.element': '水',
    'pet.pet36.element': '水',
    'pet.pet37.element': '水',
    'pet.pet41.element': '水',
    'pet.pet42.element': '水',
    'pet.pet46.element': '水',
    'pet.pet47.element': '水',
    'pet.pet51.element': '水',
    // 火屬性
    'pet.pet2.element': '火',
    'pet.pet4.element': '火',
    'pet.pet7.element': '火',
    'pet.pet9.element': '火',
    'pet.pet11.element': '火',
    'pet.pet16.element': '火',
    'pet.pet21.element': '火',
    'pet.pet23.element': '火',
    'pet.pet34.element': '火',
    'pet.pet39.element': '火',
    'pet.pet40.element': '火',
    'pet.pet44.element': '火',
    'pet.pet45.element': '火',
    // 木屬性
    'pet.pet3.element': '木',
    'pet.pet6.element': '木',
    'pet.pet8.element': '木',
    'pet.pet10.element': '木',
    'pet.pet12.element': '木',
    'pet.pet17.element': '木',
    'pet.pet20.element': '木',
    'pet.pet22.element': '木',
    'pet.pet26.element': '木',
    'pet.pet29.element': '木',
    'pet.pet43.element': '木',
    'pet.pet48.element': '木',
    'pet.pet49.element': '木',
    // 土屬性
    'pet.pet14.element': '土',
    'pet.pet15.element': '土',
    'pet.pet24.element': '土',
    'pet.pet25.element': '土',
    'pet.pet27.element': '土',
    'pet.pet28.element': '土',
    'pet.pet30.element': '土',
    'pet.pet31.element': '土',
    'pet.pet32.element': '土',
    'pet.pet33.element': '土',
    'pet.pet38.element': '土',
    'pet.pet50.element': '土',
    // BOSS 水屬性
    'pet.boss_pet_02.element': '水',
    'pet.boss_pet_07.element': '水',
    'pet.boss_pet_13.element': '水',
    'pet.boss_pet_14.element': '水',
    // BOSS 火屬性
    'pet.boss_pet_06.element': '火',
    'pet.boss_pet_12.element': '火',
    'pet.boss_pet_15.element': '火',
    'pet.boss_pet_16.element': '火',
    // BOSS 木屬性
    'pet.boss_pet_01.element': '木',
    'pet.boss_pet_03.element': '木',
    'pet.boss_pet_05.element': '木',
    'pet.boss_pet_10.element': '木',
    // BOSS 土屬性
    'pet.boss_pet_04.element': '土',
    'pet.boss_pet_08.element': '土',
    'pet.boss_pet_09.element': '土',
    'pet.boss_pet_11.element': '土',
    // 技能名稱
    'skill.bite': '咬', 'skill.bite2': '撕咬', 'skill.bite3': '強咬',
    'skill.scratch': '抓', 'skill.scratch2': '亂抓', 'skill.scratch3': '快速亂抓',
    'skill.peck': '啄擊', 'skill.peck2': '快速啄擊', 'skill.peck3': '連續猛啄',
    'skill.charge': '撞', 'skill.charge2': '衝撞', 'skill.charge3': '猛力頭槌',
    'skill.boss_bite': '咬', 'skill.boss_bite2': '猛咬', 'skill.boss_bite3': '連續咬擊',
    'skill.boss_peck': '啄', 'skill.boss_peck2': '猛啄', 'skill.boss_peck3': '連續啄擊',
    'skill.boss_punch': '打', 'skill.boss_punch2': '猛打', 'skill.boss_punch3': '連續猛打',
    'skill.boss_charge': '撞', 'skill.boss_charge2': '猛撞', 'skill.boss_charge3': '犀角衝撞',
    // 技能描述
    'skill.bite.desc': '用尖牙狠狠咬住敵人',
    'skill.bite2.desc': '憤怒地咬住敵人不放',
    'skill.bite3.desc': '以獵犬本能發動致命一咬',
    'skill.scratch.desc': '伸出利爪抓向敵人',
    'skill.scratch2.desc': '瘋狂揮舞爪子攻擊',
    'skill.scratch3.desc': '瘋狂揮舞爪子快速攻擊',
    'skill.peck.desc': '用尖嘴啄向敵人',
    'skill.peck2.desc': '快速啄擊敵人',
    'skill.peck3.desc': '連續啄擊敵人多次',
    'skill.charge.desc': '低頭用身體衝撞敵人',
    'skill.charge2.desc': '低頭用身體全力衝撞敵人',
    'skill.charge3.desc': '蓄力後以頭部猛烈撞擊',
    'skill.boss_bite.desc': '用利牙快速咬向敵人',
    'skill.boss_bite2.desc': '用利牙用力猛咬',
    'skill.boss_bite3.desc': '瘋狂連續咬擊敵人',
    'skill.boss_peck.desc': '用鳥喙快速啄向敵人',
    'skill.boss_peck2.desc': '用鳥喙用力猛啄',
    'skill.boss_peck3.desc': '瘋狂連續啄擊敵人',
    'skill.boss_punch.desc': '揮出拳頭快速打向敵人',
    'skill.boss_punch2.desc': '蓄力後全力揮拳猛打',
    'skill.boss_punch3.desc': '瘋狂連續揮拳攻擊',
    'skill.boss_charge.desc': '低頭用身體快速撞向敵人',
    'skill.boss_charge2.desc': '蓄力後全力衝撞敵人',
    'skill.boss_charge3.desc': '以鋼鐵犀角全速衝撞',
    // 戰鬥
    'battle.ap': '行動值',
    'battle.end_turn': '結束回合',
    'battle.victory': '勝利！',
    'battle.defeat': '戰鬥失敗',
    'battle.crit': '暴擊！',
    'battle.defeat.desc': '太強大，繼續升等再挑戰！',
    'battle.confirm': '確認',
    'battle.victory.desc': '精彩！旋轉轉盤獲取獎勵！',
    'battle.spin': '🎰 轉動轉盤！',
    'battle.super_effective': '效果絕佳！',
    // 屬性名稱
    'element.水': '水',
    'element.火': '火',
    'element.木': '木',
    'element.土': '土',
    // BOSS 挑戰卷確認彈窗
    'boss.ticket.confirm.title': '使用 BOSS 挑戰卷',
    'boss.ticket.confirm.desc': '確定使用挑戰卷挑戰',
    'boss.ticket.confirm.question': '嗎？',
    'boss.ticket.remaining': '剩餘挑戰卷：',
    'boss.ticket.remaining.unit': '張',
    'boss.ticket.cancel': '取消',
    'boss.ticket.confirm.btn': '確定',
    // 命運轉盤
    'wheel.title': '命運轉盤',
    'wheel.desc': '恭喜打敗',
    'wheel.desc2': '！轉動轉盤獲得獎勵！',
    'wheel.spin': '🎰 轉動！',
    'wheel.gems.result': '能量石獲得！',
    'wheel.pet.result': '獲得 BOSS 寵物！',
    'wheel.pet.owned': '已擁有 +50 💎',
    'wheel.confirm': '確認',
    'wheel.pet.label': '寵物',
    // 儲值頁面
    'iap.title': '儲值像素晶石',
    'iap.test.mode': '⚠️ 目前為測試模式，不收取真實費用',
    'iap.bonus': '贈送',
    'iap.best': '最划算',
    'iap.pack.starter': '新手包',
    'iap.pack.value': '超值包',
    'iap.pack.popular': '熱門包',
    'iap.pack.deluxe': '豪華包',
    'iap.pack.supreme': '至尊包',
    'iap.pack.royal': '王者包',
    // 任務
    'quest.daily': '每日',
    'quest.achievement': '成就',
    'quest.weekly': '週常',
    'quest.inprogress': '進行中',
    'quest.claim': '領取',
    'quest.claimed': '已領取',
    // 設定
    'settings.title': '設定',
    'settings.sound': '音效',
    'settings.bgm': 'BGM',
    'settings.volume': '音量',
    'settings.language': '語言',
    'settings.notify': '通知提醒',
    'settings.export': '匯出存檔',
    'settings.import': '匯入存檔',
    'settings.clear': '清除存檔',
    'settings.version': '遊戲版本',
    'settings.developer': '開發者',
    'settings.contact': '聯絡我們',
    'settings.sound.section': '音效 / 音樂',
    'settings.game.section': '遊戲設定',
    'settings.account.section': '帳號 / 資料',
    'settings.player.name': '玩家名稱',
    'settings.player.placeholder': '輸入你的名字',
    'settings.export.btn': '匯出',
    'settings.import.btn': '匯入',
    'settings.pet.notify': '寵物餓了提醒',
    'settings.quest.notify': '任務完成提醒',
    // 能量銀行
    'bank.title': '能量兌換銀行',
    'bank.rate': '今日匯率',
    'bank.rate.desc': '可以兌換最近一週的步數，兌換後清空列表',
    'bank.exchange': '兌換',
    'bank.owned': '你擁有的像素晶石',
    'bank.empty': '所有步數已兌換',
    'bank.empty.desc': '明天 00:00 後會新增當天步數',
    'bank.rate.unit': '能量 = 1',
    'bank.steps.unit': '步',
    'bank.exchangeable': '可兌換',
    // 稀有度
    'rarity.F': 'F',
    'rarity.R': 'R',
    'rarity.SR': 'SR',
    'rarity.SSR': 'SSR',
    // 屬性
    'stat.hp': '生命值',
    'stat.atk': '攻擊力',
    'stat.def': '防禦力',
    'stat.mood': '心情',
    'stat.hunger': '飽食',
    'stat.water': '水份',
    'stat.exp': 'EXP',
    'stat.level': '等級',
    // 食物商品
    'food.biscuit_crumbs': '餅乾屑',
    'food.biscuit': '餅乾',
    'food.corn': '玉米',
    'food.toast': '吐司',
    'food.donut': '甜甜圈',
    'food.fries': '薯條',
    'food.hotdog': '熱狗',
    'food.chicken_leg': '雞腿',
    'food.pizza': '披薩',
    'food.burger': '漢堡',
    'food.salmon': '鮭魚',
    'food.chocolate': '巧克力',
    'food.cake': '蛋糕',
    // 飲料商品
    'drink.water': '礦泉水',
    'drink.tea': '紅茶',
    'drink.green_tea': '綠茶',
    'drink.grape_juice': '葡萄汁',
    'drink.apple_juice': '蘋果汁',
    'drink.cola': '可樂',
    'drink.milk': '牛奶',
    'drink.coffee': '咖啡',
    // Toast 訊息
    'toast.level_up': '升級啦！',
    'toast.max_level': '已達等級上限！',
    'toast.no_coins': '能量石不足！',
    'toast.feed_success': '餵食成功！',
    'toast.drink_success': '飲料使用成功！',
    'toast.gacha_result': '抽獎結果',
    'toast.ticket_used': '使用挑戰卷！',
    'toast.treasure': '獲得能量石！',
    // 任務內容（每日 / 成就 / 週常）
    'quest.d1.name': '餵食寵物',     'quest.d1.desc': '使用一次食物',
    'quest.d2.name': '給寵物喝飲料', 'quest.d2.desc': '使用一次飲料',
    'quest.d3.name': '挑戰 BOSS',   'quest.d3.desc': '完成一場 BOSS 戰鬥',
    'quest.d4.name': '心情滿滿',    'quest.d4.desc': '任一寵物心情達到 80 以上',
    'quest.d5.name': '扭蛋一抽',    'quest.d5.desc': '抽一次扭蛋',
    'quest.d6.name': '出去尋寶',    'quest.d6.desc': '收集一個寶箱',
    'quest.d7.name': '兌換能量',    'quest.d7.desc': '完成一次步數兌換',
    'quest.d8.name': '免費能量石',  'quest.d8.desc': '觀看廣告獲得獎勵',
    'quest.a1.name': '初出茅廬',  'quest.a1.desc': '任一寵物達到 Lv.10',
    'quest.a2.name': '漸入佳境',  'quest.a2.desc': '任一寵物達到 Lv.20',
    'quest.a3.name': '爐火純青',  'quest.a3.desc': '任一寵物達到 Lv.30',
    'quest.a4.name': '登峰造極',  'quest.a4.desc': '任一寵物達到 Lv.50',
    'quest.a5.name': '收藏家',    'quest.a5.desc': '收集 10 隻寵物',
    'quest.a6.name': '收藏大師',  'quest.a6.desc': '收集 25 隻寵物',
    'quest.a7.name': '收藏王者',  'quest.a7.desc': '收集 51 隻寵物',
    'quest.a8.name': '初戰告捷',  'quest.a8.desc': '通關第一隻 BOSS',
    'quest.a9.name': '無人能敵',  'quest.a9.desc': '通關全部 BOSS',
    'quest.a10.name': '幸運降臨', 'quest.a10.desc': '抽中第一隻 SSR 寵物',
    'quest.a11.name': '小富翁',   'quest.a11.desc': '累積花費 1000 能量石',
    'quest.a12.name': '大富翁',   'quest.a12.desc': '累積花費 5000 能量石',
    'quest.w1.name': '戰鬥達人', 'quest.w1.desc': '完成 5 場戰鬥',
    'quest.w2.name': '扭蛋十連', 'quest.w2.desc': '累積抽 10 次扭蛋',
    'quest.w3.name': '步數達人', 'quest.w3.desc': '連續兌換步數 7 天',
  },

  'en': {
    // Navigation
    'nav.home': 'Home',
    'nav.quest': 'Quests',
    'nav.explore': 'Explore',
    'nav.shop': 'Shop',
    'nav.settings': 'Settings',
    // Home
    'home.feed': 'Feed',
    'home.drink': 'Drink',
    'home.item': 'Items',
    'home.pet': 'Pets',
    'home.info': 'Info',
    'home.collection': 'Collection',
    'home.manage': 'Manage',
    'home.focus': 'Focus',
    'toast.coming_soon': 'Coming soon!',
    // Focus Timer
    'focus.title': 'Focus',
    'focus.new': '＋ New',
    'focus.edit': 'Edit',
    'focus.delete': 'Delete',
    'focus.name': 'Task name',
    'focus.time': 'Duration (minutes)',
    'focus.start': 'Start',
    'focus.pause': 'Pause',
    'focus.resume': 'Resume',
    'focus.stop': 'Stop',
    'focus.complete': 'Focus complete!',
    'focus.back': '← Back',
    'focus.save': 'Save',
    'focus.cancel': 'Cancel',
    // Pet Detail page
    'pet.detail.title': 'Pet Detail',
    'pet.detail.stats': 'Battle Stats',
    'pet.detail.skills': 'Skills',
    'stat.rarity': 'Rarity',
    'skill.power': 'Power',
    // Pet action popup
    'pet.action.detail': 'View Detail',
    'pet.action.remove': 'Return to Bag',
    'pet.action.cancel': 'Cancel',
    // Bag
    'bag.food': 'Food',
    'bag.drink': 'Drinks',
    'bag.item': 'Items',
    'bag.pet': 'Pets',
    'bag.empty.food': 'No food in bag. Go to shop!',
    'bag.empty.drink': 'No drinks in bag. Go to shop!',
    'bag.empty.item': 'No items in bag. Go to shop!',
    'bag.empty.pet': 'No pets in bag. Try the gacha!',
    // Shop
    'shop.title': 'Shop',
    'shop.subtitle': 'Bank & Shop',
    'shop.back': '← Back',
    'shop.bank': 'Energy Bank',
    'shop.bank.desc': 'Exchange and manage your Pixel Gems',
    'shop.food.name': 'Food Shop',
    'shop.drink.name': 'Drink Shop',
    'shop.item.name': 'Item Shop',
    'shop.petshop': 'Pet Shop',
    'shop.snack': 'Snack Shop',
    'shop.style': 'Style Shop',
    'shop.gacha': 'Gacha',
    'shop.view': 'View',
    'shop.food.desc': 'Buy food',
    'shop.drink.desc': 'Buy drinks',
    'shop.item.desc': 'Buy pet items',
    'shop.gacha.desc': 'Draw rare pets',
    'shop.item.section': 'Items',
    'food.shop.title': 'Food Shop',
    'drink.shop.title': 'Drink Shop',
    // Gacha
    'gacha.title': 'Pet Gacha',
    'gacha.pool': 'Standard Pool',
    'gacha.single': 'Single Draw',
    'gacha.ten': '10x Draw',
    'gacha.ad': 'Watch Ad to Draw',
    'gacha.new': 'NEW!',
    'gacha.owned': 'Owned',
    // Ads
    'ad.watch': 'Watch Ad',
    'ad.watching': 'Ad playing...',
    'ad.reward': 'Ad Reward',
    'ad.limit': 'Daily limit reached',
    'ad.free_gacha': 'Watch Ad for Free Draw',
    'ad.count': 'Watch Ad',
    'ad.reward.toast': 'Ad Reward +50 Gems!',
    'ad.gacha.toast': 'Free draw obtained!',
    // Items
    'item.heart_candy': 'Heart Candy',
    'item.heart_candy.desc': '+10 Mood',
    'item.growth_potion': 'Growth Potion',
    'item.growth_potion.desc': '+10 EXP',
    'item.boss_ticket': 'BOSS Challenge Ticket',
    'item.boss_ticket.desc': 'Challenge any unlocked BOSS. One ticket per battle.',
    'item.boss_ticket.goto': 'Go to BOSS Battle',
    'item.use': 'Use',
    'item.super_growth': 'Super Growth Potion',
    'item.super_growth.desc': 'Instantly levels up pet to max level',
    'item.super_growth.used': 'Super Growth Potion used! Pet reached max level!',
    'item.super_growth.maxed': 'Pet is already at max level!',
    // Explore
    'explore.title': 'Explore',
    'explore.subtitle': 'Choose Explore Mode',
    'explore.world': 'Explore World',
    'explore.boss': 'BOSS Battle',
    'explore.mystery': 'Mystery Shop',
    'explore.go': 'Go Outside',
    'explore.go.desc': 'Collect treasure boxes on real map',
    'explore.boss.desc': 'Challenge powerful BOSSes for rare rewards',
    // BOSS
    'boss.title': 'BOSS Battle',
    'boss.locked': '🔒 Locked',
    'boss.ticket': '🎫 Use Ticket',
    'boss.need_ticket': '🎫 Need Ticket',
    // Pet names
    'pet.pet1.name': 'Puppy', 'pet.pet2.name': 'Shiba Inu', 'pet.pet3.name': 'Dachshund', 'pet.pet4.name': 'Corgi',
    'pet.pet5.name': 'Beagle', 'pet.pet6.name': 'Mixed Breed', 'pet.pet7.name': 'Poodle', 'pet.pet8.name': 'Bichon Frise',
    'pet.pet9.name': 'German Shepherd', 'pet.pet10.name': 'Border Collie', 'pet.pet11.name': 'Bernese Mountain Dog', 'pet.pet12.name': 'Sheepdog',
    'pet.pet13.name': 'Orange Cat', 'pet.pet14.name': 'Gray Cat', 'pet.pet15.name': 'White Cat', 'pet.pet16.name': 'Black Cat',
    'pet.pet17.name': 'British Shorthair', 'pet.pet18.name': 'Milk Cat', 'pet.pet19.name': 'Ragdoll', 'pet.pet20.name': 'Calico Cat',
    'pet.pet21.name': 'Persian Cat', 'pet.pet22.name': 'Maine Coon', 'pet.pet23.name': 'Fox', 'pet.pet24.name': 'Piglet',
    'pet.pet25.name': 'Musk Pig', 'pet.pet26.name': 'Gray Rabbit', 'pet.pet27.name': 'Black Rabbit', 'pet.pet28.name': 'White Rabbit',
    'pet.pet29.name': 'Dutch Rabbit', 'pet.pet30.name': 'Kunekune Pig', 'pet.pet31.name': 'Mini Pig', 'pet.pet32.name': 'Lop Rabbit',
    'pet.pet33.name': 'Hereford Cow', 'pet.pet34.name': 'Lovebird', 'pet.pet35.name': 'Eclectus Parrot', 'pet.pet36.name': 'Budgerigar',
    'pet.pet37.name': 'Cockatiel', 'pet.pet38.name': 'African Grey Parrot', 'pet.pet39.name': 'Cockatoo', 'pet.pet40.name': 'Chicken',
    'pet.pet41.name': 'Duckling', 'pet.pet42.name': 'Capybara', 'pet.pet43.name': 'Tree Sparrow', 'pet.pet44.name': 'Red-headed Tit',
    'pet.pet45.name': 'Yellow Cow', 'pet.pet46.name': 'Holstein Cow', 'pet.pet47.name': 'Raccoon', 'pet.pet48.name': 'Reeves Muntjac',
    'pet.pet49.name': 'Sika Deer', 'pet.pet50.name': 'Sheep', 'pet.pet51.name': 'Red Panda',
    // BOSS pet names
    'pet.boss_pet_01.name': 'Macaw', 'pet.boss_pet_02.name': 'Python', 'pet.boss_pet_03.name': 'Ostrich', 'pet.boss_pet_04.name': 'Wolf',
    'pet.boss_pet_05.name': 'Kangaroo', 'pet.boss_pet_06.name': 'Cheetah', 'pet.boss_pet_07.name': 'Hippo', 'pet.boss_pet_08.name': 'Rhinoceros',
    'pet.boss_pet_09.name': 'Brown Bear', 'pet.boss_pet_10.name': 'Owl', 'pet.boss_pet_11.name': 'Gorilla', 'pet.boss_pet_12.name': 'Tibetan Mastiff',
    'pet.boss_pet_13.name': 'Crocodile', 'pet.boss_pet_14.name': 'Eagle', 'pet.boss_pet_15.name': 'Lion', 'pet.boss_pet_16.name': 'Tiger',
    // Pet elements (element names are not translated, distinguished by icon)
    // Water
    'pet.pet1.element': '水',
    'pet.pet5.element': '水',
    'pet.pet13.element': '水',
    'pet.pet18.element': '水',
    'pet.pet19.element': '水',
    'pet.pet35.element': '水',
    'pet.pet36.element': '水',
    'pet.pet37.element': '水',
    'pet.pet41.element': '水',
    'pet.pet42.element': '水',
    'pet.pet46.element': '水',
    'pet.pet47.element': '水',
    'pet.pet51.element': '水',
    // Fire
    'pet.pet2.element': '火',
    'pet.pet4.element': '火',
    'pet.pet7.element': '火',
    'pet.pet9.element': '火',
    'pet.pet11.element': '火',
    'pet.pet16.element': '火',
    'pet.pet21.element': '火',
    'pet.pet23.element': '火',
    'pet.pet34.element': '火',
    'pet.pet39.element': '火',
    'pet.pet40.element': '火',
    'pet.pet44.element': '火',
    'pet.pet45.element': '火',
    // Wood
    'pet.pet3.element': '木',
    'pet.pet6.element': '木',
    'pet.pet8.element': '木',
    'pet.pet10.element': '木',
    'pet.pet12.element': '木',
    'pet.pet17.element': '木',
    'pet.pet20.element': '木',
    'pet.pet22.element': '木',
    'pet.pet26.element': '木',
    'pet.pet29.element': '木',
    'pet.pet43.element': '木',
    'pet.pet48.element': '木',
    'pet.pet49.element': '木',
    // Earth
    'pet.pet14.element': '土',
    'pet.pet15.element': '土',
    'pet.pet24.element': '土',
    'pet.pet25.element': '土',
    'pet.pet27.element': '土',
    'pet.pet28.element': '土',
    'pet.pet30.element': '土',
    'pet.pet31.element': '土',
    'pet.pet32.element': '土',
    'pet.pet33.element': '土',
    'pet.pet38.element': '土',
    'pet.pet50.element': '土',
    // BOSS Water
    'pet.boss_pet_02.element': '水',
    'pet.boss_pet_07.element': '水',
    'pet.boss_pet_13.element': '水',
    'pet.boss_pet_14.element': '水',
    // BOSS Fire
    'pet.boss_pet_06.element': '火',
    'pet.boss_pet_12.element': '火',
    'pet.boss_pet_15.element': '火',
    'pet.boss_pet_16.element': '火',
    // BOSS Wood
    'pet.boss_pet_01.element': '木',
    'pet.boss_pet_03.element': '木',
    'pet.boss_pet_05.element': '木',
    'pet.boss_pet_10.element': '木',
    // BOSS Earth
    'pet.boss_pet_04.element': '土',
    'pet.boss_pet_08.element': '土',
    'pet.boss_pet_09.element': '土',
    'pet.boss_pet_11.element': '土',
    // Skill names
    'skill.bite': 'Bite', 'skill.bite2': 'Rip', 'skill.bite3': 'Strong Bite',
    'skill.scratch': 'Scratch', 'skill.scratch2': 'Claw Frenzy', 'skill.scratch3': 'Swift Claw',
    'skill.peck': 'Peck', 'skill.peck2': 'Quick Peck', 'skill.peck3': 'Peck Barrage',
    'skill.charge': 'Charge', 'skill.charge2': 'Full Charge', 'skill.charge3': 'Headbutt',
    'skill.boss_bite': 'Bite', 'skill.boss_bite2': 'Fierce Bite', 'skill.boss_bite3': 'Bite Barrage',
    'skill.boss_peck': 'Peck', 'skill.boss_peck2': 'Fierce Peck', 'skill.boss_peck3': 'Peck Barrage',
    'skill.boss_punch': 'Punch', 'skill.boss_punch2': 'Fierce Punch', 'skill.boss_punch3': 'Punch Barrage',
    'skill.boss_charge': 'Charge', 'skill.boss_charge2': 'Fierce Charge', 'skill.boss_charge3': 'Horn Charge',
    // Skill descriptions
    'skill.bite.desc': 'Bites the enemy hard with sharp fangs',
    'skill.bite2.desc': 'Angrily clamps down on the enemy',
    'skill.bite3.desc': 'A deadly bite driven by hunting instinct',
    'skill.scratch.desc': 'Extends claws to scratch the enemy',
    'skill.scratch2.desc': 'Wildly swings claws to attack',
    'skill.scratch3.desc': 'Rapidly swings claws in a frenzy',
    'skill.peck.desc': 'Pecks at the enemy with a sharp beak',
    'skill.peck2.desc': 'Rapidly pecks at the enemy',
    'skill.peck3.desc': 'Continuously pecks the enemy multiple times',
    'skill.charge.desc': 'Lowers head and charges into the enemy',
    'skill.charge2.desc': 'Lowers head and charges at full force',
    'skill.charge3.desc': 'Charges with a powerful headbutt',
    'skill.boss_bite.desc': 'Lunges at the enemy with sharp fangs',
    'skill.boss_bite2.desc': 'Bites down with tremendous force',
    'skill.boss_bite3.desc': 'Bites the enemy repeatedly in a frenzy',
    'skill.boss_peck.desc': 'Strikes the enemy with a sharp beak',
    'skill.boss_peck2.desc': 'Pecks down with tremendous force',
    'skill.boss_peck3.desc': 'Pecks the enemy repeatedly in a frenzy',
    'skill.boss_punch.desc': 'Throws a quick punch at the enemy',
    'skill.boss_punch2.desc': 'Winds up and unleashes a powerful punch',
    'skill.boss_punch3.desc': 'Unleashes a flurry of punches',
    'skill.boss_charge.desc': 'Lowers head and rushes at the enemy',
    'skill.boss_charge2.desc': 'Winds up and charges with full force',
    'skill.boss_charge3.desc': 'Charges at full speed with its steel-hard horn',
    // Battle
    'battle.ap': 'AP',
    'battle.end_turn': 'End Turn',
    'battle.victory': 'Victory!',
    'battle.defeat': 'Defeated',
    'battle.crit': 'Critical!',
    'battle.defeat.desc': 'is too powerful. Level up and try again!',
    'battle.confirm': 'OK',
    'battle.victory.desc': 'Spin the wheel to get rewards!',
    'battle.spin': '🎰 Spin Wheel!',
    'battle.super_effective': 'Super Effective!',
    // Element names
    'element.水': 'Water',
    'element.火': 'Fire',
    'element.木': 'Wood',
    'element.土': 'Earth',
    // BOSS Ticket Confirm Modal
    'boss.ticket.confirm.title': 'Use BOSS Challenge Ticket',
    'boss.ticket.confirm.desc': 'Use a ticket to challenge',
    'boss.ticket.confirm.question': '?',
    'boss.ticket.remaining': 'Remaining tickets:',
    'boss.ticket.remaining.unit': '',
    'boss.ticket.cancel': 'Cancel',
    'boss.ticket.confirm.btn': 'Confirm',
    // Fortune Wheel
    'wheel.title': 'Fortune Wheel',
    'wheel.desc': 'Congratulations! You defeated',
    'wheel.desc2': '! Spin the wheel for rewards!',
    'wheel.spin': '🎰 Spin!',
    'wheel.gems.result': 'Gems obtained!',
    'wheel.pet.result': 'BOSS Pet obtained!',
    'wheel.pet.owned': 'Already owned +50 💎',
    'wheel.confirm': 'OK',
    'wheel.pet.label': 'Pet',
    // IAP Store
    'iap.title': 'Top Up Pixel Gems',
    'iap.test.mode': '⚠️ Test mode - no real charges',
    'iap.bonus': 'Bonus',
    'iap.best': 'Best Value',
    'iap.pack.starter': 'Starter Pack',
    'iap.pack.value': 'Value Pack',
    'iap.pack.popular': 'Popular Pack',
    'iap.pack.deluxe': 'Deluxe Pack',
    'iap.pack.supreme': 'Supreme Pack',
    'iap.pack.royal': 'Royal Pack',
    // Quest
    'quest.daily': 'Daily',
    'quest.achievement': 'Achievement',
    'quest.weekly': 'Weekly',
    'quest.inprogress': 'In Progress',
    'quest.claim': 'Claim',
    'quest.claimed': 'Claimed',
    // Settings
    'settings.title': 'Settings',
    'settings.sound': 'Sound',
    'settings.bgm': 'BGM',
    'settings.volume': 'Volume',
    'settings.language': 'Language',
    'settings.notify': 'Notifications',
    'settings.export': 'Export Save',
    'settings.import': 'Import Save',
    'settings.clear': 'Clear Save',
    'settings.version': 'Version',
    'settings.developer': 'Developer',
    'settings.contact': 'Contact Us',
    'settings.sound.section': 'Sound / Music',
    'settings.game.section': 'Game Settings',
    'settings.account.section': 'Account / Data',
    'settings.player.name': 'Player Name',
    'settings.player.placeholder': 'Enter your name',
    'settings.export.btn': 'Export',
    'settings.import.btn': 'Import',
    'settings.pet.notify': 'Pet Hungry Alert',
    'settings.quest.notify': 'Quest Complete Alert',
    // Bank
    'bank.title': 'Energy Exchange Bank',
    'bank.rate': 'Today\'s Rate',
    'bank.rate.desc': 'Exchange steps from the past week. List clears after exchange.',
    'bank.exchange': 'Exchange',
    'bank.owned': 'Your Pixel Gems',
    'bank.empty': 'All steps exchanged',
    'bank.empty.desc': 'New steps will be added tomorrow at 00:00',
    'bank.rate.unit': 'Energy = 1',
    'bank.steps.unit': 'steps',
    'bank.exchangeable': 'Exchangeable',
    // Rarity
    'rarity.F': 'F',
    'rarity.R': 'R',
    'rarity.SR': 'SR',
    'rarity.SSR': 'SSR',
    // Stats
    'stat.hp': 'HP',
    'stat.atk': 'ATK',
    'stat.def': 'DEF',
    'stat.mood': 'Mood',
    'stat.hunger': 'Hunger',
    'stat.water': 'Water',
    'stat.exp': 'EXP',
    'stat.level': 'Level',
    // Food items
    'food.biscuit_crumbs': 'Biscuit Crumbs',
    'food.biscuit': 'Biscuit',
    'food.corn': 'Corn',
    'food.toast': 'Toast',
    'food.donut': 'Donut',
    'food.fries': 'French Fries',
    'food.hotdog': 'Hot Dog',
    'food.chicken_leg': 'Chicken Leg',
    'food.pizza': 'Pizza',
    'food.burger': 'Burger',
    'food.salmon': 'Salmon',
    'food.chocolate': 'Chocolate',
    'food.cake': 'Cake',
    // Drink items
    'drink.water': 'Mineral Water',
    'drink.tea': 'Black Tea',
    'drink.green_tea': 'Green Tea',
    'drink.grape_juice': 'Grape Juice',
    'drink.apple_juice': 'Apple Juice',
    'drink.cola': 'Cola',
    'drink.milk': 'Milk',
    'drink.coffee': 'Coffee',
    // Toast
    'toast.level_up': 'Level Up!',
    'toast.max_level': 'Max Level Reached!',
    'toast.no_coins': 'Not enough gems!',
    'toast.feed_success': 'Fed successfully!',
    'toast.drink_success': 'Drink used!',
    'toast.gacha_result': 'Gacha Result',
    'toast.ticket_used': 'Ticket used!',
    'toast.treasure': 'Gems obtained!',
    // Quest content (daily / achievement / weekly)
    'quest.d1.name': 'Feed Pet',         'quest.d1.desc': 'Use food once',
    'quest.d2.name': 'Give Pet a Drink', 'quest.d2.desc': 'Use a drink once',
    'quest.d3.name': 'Challenge BOSS',   'quest.d3.desc': 'Complete one BOSS battle',
    'quest.d4.name': 'Mood Boost',       'quest.d4.desc': "Any pet's mood reaches 80+",
    'quest.d5.name': 'One Gacha Pull',   'quest.d5.desc': 'Pull the gacha once',
    'quest.d6.name': 'Treasure Hunt',    'quest.d6.desc': 'Collect one treasure chest',
    'quest.d7.name': 'Exchange Energy',  'quest.d7.desc': 'Complete one step exchange',
    'quest.d8.name': 'Free Gems',        'quest.d8.desc': 'Watch an ad for a reward',
    'quest.a1.name': 'First Steps',      'quest.a1.desc': 'Any pet reaches Lv.10',
    'quest.a2.name': 'Getting Stronger', 'quest.a2.desc': 'Any pet reaches Lv.20',
    'quest.a3.name': 'Masterful',        'quest.a3.desc': 'Any pet reaches Lv.30',
    'quest.a4.name': 'Peak Performance', 'quest.a4.desc': 'Any pet reaches Lv.50',
    'quest.a5.name': 'Collector',        'quest.a5.desc': 'Collect 10 pets',
    'quest.a6.name': 'Master Collector', 'quest.a6.desc': 'Collect 25 pets',
    'quest.a7.name': 'Collection King',  'quest.a7.desc': 'Collect 51 pets',
    'quest.a8.name': 'First Victory',    'quest.a8.desc': 'Clear your first BOSS',
    'quest.a9.name': 'Unstoppable',      'quest.a9.desc': 'Clear all BOSSes',
    'quest.a10.name': 'Lucky Draw',      'quest.a10.desc': 'Pull your first SSR pet',
    'quest.a11.name': 'Small Fortune',   'quest.a11.desc': 'Spend 1000 gems total',
    'quest.a12.name': 'Big Fortune',     'quest.a12.desc': 'Spend 5000 gems total',
    'quest.w1.name': 'Battle Expert',    'quest.w1.desc': 'Complete 5 battles',
    'quest.w2.name': 'Gacha x10',        'quest.w2.desc': 'Pull the gacha 10 times total',
    'quest.w3.name': 'Step Master',      'quest.w3.desc': 'Exchange steps 7 days in a row',
  },

};

// ─── Active Language State ──────────────────────────────────────────────────
let currentLang = localStorage.getItem('language') || 'zh-TW';

const t = (key) => {
  const langData = LANG_DATA[currentLang];
  const fallback = LANG_DATA['zh-TW'];
  return (langData && langData[key]) || fallback[key] || key;
};

const setLang = (lang) => {
  currentLang = lang;
  localStorage.setItem('language', lang);
  applyLang(); // 不再 location.reload()，直接套用
};

// ─── DOM Binding: data-i18n / data-i18n-placeholder / data-lang ────────────
const applyLang = () => {
  // 掃描所有 data-i18n 元素自動替換文字
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const translation = t(key);
    if (translation) el.textContent = translation;
  });

  // placeholder 支援
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    const translation = t(key);
    if (translation) el.placeholder = translation;
  });

  // 更新語言選擇按鈕樣式
  document.querySelectorAll('[data-lang]').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === currentLang);
  });
};

document.addEventListener('DOMContentLoaded', applyLang);
